"""Add Department.

Revision ID: 02407327ff08
Revises: 7791b62cae1f
Create Date: 2024-07-01 09:17:28.803758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02407327ff08'
down_revision = '7791b62cae1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
